### ISSUE TITLE
Pre-built binaries don't work in the node 14 containers

### ISSUE THREAD

**Issue by willstott101** [zeromq/zeromq.js#472] opened 2021-05-24 18:42 UTC
The alpine containers segfault as-per #470

The other debian containers don't have a new enough glibcxx (newest available there is glibcxx 3.4.22). This package seems to expect 3.4.26

**Comment by willstott101** [comment] 2021-05-24 18:46
Same problem with the glibcxx version for node 16 container also

**Comment by aminya** [comment] 2021-05-24 19:47
Duplicate of #470

**Closed by aminya** 2021-05-24 19:47 UTC
Labels: bug
