### ISSUE TITLE
Curve

### ISSUE THREAD

**Issue by muscleman** [zeromq/zeromq.js#654] opened 2024-09-01 13:41 UTC
either an option to include curve with instructions

or

instructions to implement curve ourselves

**Comment by aminya** [comment] 2024-10-02 20:41
Duplicate of #640 

You can expedite the process by sponsoring the project
https://github.com/sponsors/aminya
https://polar.sh/aminya/
https://www.patreon.com/aminya

**Closed by aminya** 2024-10-02 20:41 UTC
Labels: enhancement
