### ISSUE TITLE
[5.x] Error reporting not working

### ISSUE THREAD

**Issue by gastmeier** [zeromq/zeromq.js#465] opened 2021-04-26 17:29 UTC
Im am using version 5.x. Here is what i did:

```
let socket = zeromq.createSocket('dealer')
socket.monitor()
```

Now do i use `bind()` or `connect()`? What is the difference?

The next question is, how to catch errors with these functions? I am using `connect` and i bound to every event, which i had to find out by studying the source code, and i am getting the following output (ip address obliterated):

```
connect_delay 36 tcp://xx.xx.xx.xx:xxxx undefined
connect 39 tcp://xx.xx.xx.xx:xxxx undefined
disconnect 39 tcp://xx.xx.xx.xx:xxxx undefined
connect_retry 155 tcp://xx.xx.xx.xx:xxxx undefined
connect_delay 36 tcp://xx.xx.xx.xx:xxxx undefined
connect 39 tcp://xx.xx.xx.xx:xxxx undefined
disconnect 39 tcp://xx.xx.xx.xx:xxxx undefined
connect_retry 173 tcp://xx.xx.xx.xx:xxxx undefined
connect_delay 36 tcp://xx.xx.xx.xx:xxxx undefined
connect 41 tcp://xx.xx.xx.xx:xxxx undefined
disconnect 41 tcp://xx.xx.xx.xx:xxxx undefined
connect_retry 130 tcp://xx.xx.xx.xx:xxxx undefined
connect_delay 36 tcp://xx.xx.xx.xx:xxxx undefined
connect 39 tcp://xx.xx.xx.xx:xxxx undefined
disconnect 39 tcp://xx.xx.xx.xx:xxxx undefined
connect_retry 144 tcp://xx.xx.xx.xx:xxxx undefined
connect_delay 36 tcp://xx.xx.xx.xx:xxxx undefined
connect 41 tcp://xx.xx.xx.xx:xxxx undefined
disconnect 41 tcp://xx.xx.xx.xx:xxxx undefined
connect_retry 171 tcp://xx.xx.xx.xx:xxxx undefined
connect_delay 36 tcp://xx.xx.xx.xx:xxxx undefined
connect 41 tcp://xx.xx.xx.xx:xxxx undefined
disconnect 41 tcp://xx.xx.xx.xx:xxxx undefined
```

I printed the three arguments that are given to me, the message id, the address and an error object. The error object is undefined for every event, which is strange, because obviously, something is not working. What should does this output tell me? I also have a working ZMQ script in Python which proves that the server i want to connect to is working. I want to achieve the same results in Node.

**Comment by gastmeier** [comment] 2021-04-26 17:46
Posed differently, i want to recreate this Python script here. I am really no beginner in programming, by far not, but i can't get it done.

```
#!/usr/bin/env python

import sys
import time
import struct
import argparse
import uuid
import threading
import Queue

import logging
logging.basicConfig( format='%(message)s', level=logging.DEBUG )

import zmq

import unittest

def _readSocketEvent( msg ):
    # NOTE: little endian - hopefully that's not platform specific?
    event_id = struct.unpack( '<H', msg[:2] )[0]
    # NOTE: is it possible I would get a bitfield?
    event_names = {
        zmq.EVENT_ACCEPTED : 'EVENT_ACCEPTED',
        zmq.EVENT_ACCEPT_FAILED : 'EVENT_ACCEPT_FAILED',
        zmq.EVENT_BIND_FAILED : 'EVENT_BIND_FAILED',
        zmq.EVENT_CLOSED : 'EVENT_CLOSED',
        zmq.EVENT_CLOSE_FAILED : 'EVENT_CLOSE_FAILED',
        zmq.EVENT_CONNECTED : 'EVENT_CONNECTED',
        zmq.EVENT_CONNECT_DELAYED : 'EVENT_CONNECT_DELAYED',
        zmq.EVENT_CONNECT_RETRIED : 'EVENT_CONNECT_RETRIED',
        zmq.EVENT_DISCONNECTED : 'EVENT_DISCONNECTED',
        zmq.EVENT_LISTENING : 'EVENT_LISTENING',
        zmq.EVENT_MONITOR_STOPPED : 'EVENT_MONITOR_STOPPED',
    }
    event_name = event_names[ event_id ] if event_names.has_key( event_id ) else '%d' % event_id
    event_value = struct.unpack( '<I', msg[2:] )[0]
    return ( event_id, event_name, event_value )

def _checkMonitor( monitor ):
    try:
        event_monitor = monitor.recv( zmq.NOBLOCK )
    except zmq.Again:
        #logging.debug( 'again' )
        return

    ( event_id, event_name, event_value ) = _readSocketEvent( event_monitor )
    event_monitor_endpoint = monitor.recv( zmq.NOBLOCK )
    logging.info( 'monitor: %s %d endpoint %s' % ( event_name, event_value, event_monitor_endpoint ) )
    return ( event_id, event_value )

# start a thread, read a queue that will read input lines
def setupInputQueue():
    def waitStdin( q ):
        while ( True ):
            l = sys.stdin.readline()
            q.put( l )
    q = Queue.Queue()
    t = threading.Thread( target = waitStdin, args = ( q, ) )
    t.daemon = True
    t.start()
    return q

HOST = 'tcp://127.0.0.1:27961'
POLL_TIMEOUT = 100

def WriteMessageFormatted( message ):
    # Skip empty messages
    if len( message ) == 0:
        return

    # Strip unnecessary chars
    message = message.replace( "\n", "" )
    message = message.replace( "\\n", "", )
    message = message.replace( chr(25), "" )

    # Use mIRC color codes
    message = message.replace( "^0", chr(3) + "0,01" )  # black
    message = message.replace( "^1", chr(3) + "4,01" )  # red
    message = message.replace( "^2", chr(3) + "9,01" )  # green
    message = message.replace( "^3", chr(3) + "8,01" )  # yellow
    message = message.replace( "^4", chr(3) + "12,01" ) # blue
    message = message.replace( "^5", chr(3) + "11,01" ) # cyan
    message = message.replace( "^6", chr(3) + "13,01" ) # magenta
    message = message.replace( "^7", chr(3) + "0,01" )  # white

    # Strip broadcast statement
    if message[:10] == "broadcast:":
        message = message[11:]

    # Strip print statement
    if message[:7] == "print \"":
        message = message[7:-1]

    # Write
    logging.info( message )

if ( __name__ == '__main__' ):
    logging.info( 'zmq python bindings %s, libzmq version %s' % ( repr( zmq.__version__ ), zmq.zmq_version() ) )
    parser = argparse.ArgumentParser( description = 'Verbose QuakeLive server statistics' )
    parser.add_argument( '--host', default = HOST, help = 'ZMQ URI to connect to. Defaults to %s' % HOST )
    parser.add_argument( '--password', required = False )
    parser.add_argument( '--identity', default = uuid.uuid1().hex, help = 'Specify the socket identity. Random UUID used by default' )
    args = parser.parse_args()
    # TODO: put a curses or a tk interface on top of this
    q = setupInputQueue()
    try:
        ctx = zmq.Context()
        socket = ctx.socket( zmq.DEALER )
        monitor = socket.get_monitor_socket( zmq.EVENT_ALL )
        if ( args.password is not None ):
            logging.info( 'setting password for access' )
            socket.plain_username = 'rcon'
            socket.plain_password = args.password
            socket.zap_domain = 'rcon'
        socket.setsockopt( zmq.IDENTITY, args.identity )
        socket.connect( args.host )
        print( 'Connecting to %s' % args.host )
        while ( True ):
            event = socket.poll( POLL_TIMEOUT )
            event_monitor = _checkMonitor( monitor )
            if ( event_monitor is not None and event_monitor[0] == zmq.EVENT_CONNECTED ):
                # application layer protocol - notify the server of our presence
                logging.info( 'Registering with the server.' )
                socket.send( 'register' )

            while ( not q.empty() ):
                l = q.get()

                if (l == 'exit\n'):
                    logging.info( 'exiting...' )
                    exit()

                logging.info( 'sending command: %s' % repr( l ) )
                socket.send( l )

            if ( event == 0 ):
                continue

            while ( True ):
                try:
                    msg = socket.recv( zmq.NOBLOCK )
                except zmq.error.Again:
                    break
                except Exception as e:
                    logging.info( e )
                    break
                else:
                    WriteMessageFormatted( msg )
    except Exception as e:
        logging.info( e )
```

**Comment by aminya** [comment] 2021-04-26 18:22
I added a couple of comments in #464 about some of your questions.

**Comment by gastmeier** [comment] 2021-04-26 18:32
Thank you @aminya . Could you please help me a little to get this thing running. I am really desperate.

If you look at this code and then compare it to the Python version:

```typescript
let socket = zeromq.createSocket('dealer')

socket.plain_username = 'rcon'
socket.plain_password = '...'
socket.zap_domain = 'rcon'

socket.connect('tcp://95.216.19.32:28962')
socket.send('say Hello')
```

Should that not be exactly the same as in the Python version? Like i said, the Python version works. With my code i am getting the output

```
connect_delay 36 tcp://xx.xx.xx.xx:xxxx undefined
connect 39 tcp://xx.xx.xx.xx:xxxx undefined
```

Through this code here:

```typescript
socket.on('connect', function(eventValue, eventEndpointAddrress, error) {
  console.log('connect', eventValue, eventEndpointAddrress, error)
})

socket.on('connected', function(eventValue, eventEndpointAddrress, error) {
  console.log('connected', eventValue, eventEndpointAddrress, error)
})

socket.on('connect_delay', function(eventValue, eventEndpointAddrress, error) {
  console.log('connect_delay', eventValue, eventEndpointAddrress, error)
})

socket.on('connect_retry', function(eventValue, eventEndpointAddrress, error) {
  console.log('connect_retry', eventValue, eventEndpointAddrress, error)
})

socket.on('listen', function(eventValue, eventEndpointAddrress, error) {
  console.log('listen', eventValue, eventEndpointAddrress, error)
})

socket.on('bind', function(eventValue, eventEndpointAddrress, error) {
  console.log('bind', eventValue, eventEndpointAddrress, error)
})

socket.on('bind_error', function(eventValue, eventEndpointAddrress, error) {
  console.log('bind_error', eventValue, eventEndpointAddrress, error)
})

socket.on('accept', function(eventValue, eventEndpointAddrress, error) {
  console.log('accept', eventValue, eventEndpointAddrress, error)
})

socket.on('accept_error', function(eventValue, eventEndpointAddrress, error) {
  console.log('accept_error', eventValue, eventEndpointAddrress, error)
})

socket.on('close', function(eventValue, eventEndpointAddrress, error) {
  console.log('close', eventValue, eventEndpointAddrress, error)
})

socket.on('close_error', function(eventValue, eventEndpointAddrress, error) {
  console.log('close_error', eventValue, eventEndpointAddrress, error)
})

socket.on('disconnect', function(eventValue, eventEndpointAddrress, error) {
  console.log('disconnect', eventValue, eventEndpointAddrress, error)
})

socket.on('message', function(message) {
  console.log('message', message)
})
```

**Comment by aminya** [comment] 2021-04-26 18:35
You're welcome. 

When the promise that `bind` returns is resolved, you will be sure that the connection is made. For testing, maybe use `bindSync(...)` because it waits until it is connected. For the production use `await bind(...)`.

If you prefer to use `connect`, then remember that it connects in the background, so you will not know if it is connected. You should add `on` listeners. 

About the error object being `undefined`, maybe @n-riesco can help more.

**Comment by gastmeier** [comment] 2021-04-26 18:58
@aminya It is getting better. I get an error message.

```
close 39 tcp://95.216.19.32:28962 undefined
error [Error: Can't assign requested address]
bind_error 49 95.216.19.32:28962 [Error: Resource temporarily unavailable]
```

```typescript
let socket = zeromq.createSocket('dealer')

socket.plain_username = 'rcon'
socket.plain_password = 'quakeliveserverstandards'
socket.zap_domain = 'rcon'
socket.identity = 'test'

socket.monitor()

// removed socket.on() code

socket.bind('tcp://95.216.19.32:28962', error => {
  console.log('error', error)
  socket.send('say Hello')
})
```

:(

**Comment by gastmeier** [comment] 2021-04-26 19:15
Another question is, why is there no connected event?

```typescript
var events = exports.events = {
    1:   "connect"       // zmq.ZMQ_EVENT_CONNECTED
  , 2:   "connect_delay" // zmq.ZMQ_EVENT_CONNECT_DELAYED
  , 4:   "connect_retry" // zmq.ZMQ_EVENT_CONNECT_RETRIED
  , 8:   "listen"        // zmq.ZMQ_EVENT_LISTENING
  , 16:  "bind_error"    // zmq.ZMQ_EVENT_BIND_FAILED
  , 32:  "accept"        // zmq.ZMQ_EVENT_ACCEPTED
  , 64:  "accept_error"  // zmq.ZMQ_EVENT_ACCEPT_FAILED
  , 128: "close"         // zmq.ZMQ_EVENT_CLOSED
  , 256: "close_error"   // zmq.ZMQ_EVENT_CLOSE_FAILED
  , 512: "disconnect"    // zmq.ZMQ_EVENT_DISCONNECTED
}
```

**Comment by gastmeier** [comment] 2021-04-26 20:10
> Another question is, why is there no connected event?
> 
> ```ts
> var events = exports.events = {
>     1:   "connect"       // zmq.ZMQ_EVENT_CONNECTED
>   , 2:   "connect_delay" // zmq.ZMQ_EVENT_CONNECT_DELAYED
>   , 4:   "connect_retry" // zmq.ZMQ_EVENT_CONNECT_RETRIED
>   , 8:   "listen"        // zmq.ZMQ_EVENT_LISTENING
>   , 16:  "bind_error"    // zmq.ZMQ_EVENT_BIND_FAILED
>   , 32:  "accept"        // zmq.ZMQ_EVENT_ACCEPTED
>   , 64:  "accept_error"  // zmq.ZMQ_EVENT_ACCEPT_FAILED
>   , 128: "close"         // zmq.ZMQ_EVENT_CLOSED
>   , 256: "close_error"   // zmq.ZMQ_EVENT_CLOSE_FAILED
>   , 512: "disconnect"    // zmq.ZMQ_EVENT_DISCONNECTED
> }
> ```

Look at how you place the commas. How cool do you think you are? Wtf? This looks ugly. Nobody needed this ugly solution for commas. Why do you give that to the world?

**Comment by gastmeier** [comment] 2021-04-26 20:45
```js
setTimeout(function() {
        pub.send('js is cool');
        pub.send('ruby is meh');
        pub.send('py is pretty cool');
        pub.send('luna is cool too');
      }, 100.0);
```

Just no comment.

**Comment by overflowz** [comment] 2021-04-26 21:42
@gastmeier all I'm gonna say is that contributions are welcome. I'm not sorry if things do not work around you, sir.

**Comment by gastmeier** [comment] 2021-04-26 21:51
Writing a documentation, creating Typescript compatible code, adding an await/async interface, creating comprehensive examples that actually explain things to people. This is the work of one weekend or two. I come here and i just want to use this code. You cannot expect that other people do your work. You were the people that wanted free fame by publishing things free of charge, instead of building a business around it. Now you got the customers you wanted and now you have to go on and satisfy the customers you wanted for free. Or just let it be in the first place. Or build a business around your code where you are actually able to pay people so that they can work full time and can produce quality code and quality documentation. This half-assed approach of sniffing entrepreneurial air is just that, half-assed. If you decision was to not earn money and to do it for free, that does not protect you from real customer needs.

**Comment by overflowz** [comment] 2021-04-26 21:54
Just for your information, I've never been part of ZeroMQ, in fact, I just found this library by myself and want to play with it. Whenever I'm facing any issues, I'm contributing (you wanted typescript support, here it is: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52566).

**Comment by gastmeier** [comment] 2021-04-26 22:03
Yes i saw that. And i read what you wrote about it. Sorry that i have to tell you that this is also just another half-assed approach.

> please do keep in mind that these are minimal types. It would be nice to have proper values for example for the setsockopt (right now, I made all of them of type unknown).

What the fuck are you proud of? Investing like 5 minutes so that you can claim you contributed to open source? Half-assed TypeScript type definitions?

Like i said, this is what this whole project here seems to be about. Doing it half-assed, trying to be famous. Sorry that i attack you too, but things that are laying there so obvious. I don't want to use your half-assed TypeScript definitions. I am using the definitions for version 4, because for version 5, nobody cared to create TypeScript definitions. Because why? While we are about to enter version 6, version 5 just did not receive definitions. If this was my code it would take me about 1 hour to create those. And if this was my code i would be embarrassed to present half-assed solutions to the world.

**Comment by gastmeier** [comment] 2021-04-26 22:11
@overflowz And another thing. @aminya tells me to use await when i use bind. Look at the code.

```js
Socket.prototype.bind = function(addr, cb) {
  var self = this;
  this._zmq.bind(addr, function(err) {
    if (err) {
      return cb && cb(err);
    }

    self._flushReads();
    self._flushWrites();

    self.emit('bind', addr);
    cb && cb();
  });
  return this;
};
```

Can you see any Promise being returned? Also he does not know what bind and connect is for. I don't know either but there seems to be a difference, which of course the documentation, which for version 5 does not even exist, cannot make clear. Wtf? He is contributing to the code... I mean its nice that he answers to me, though in an arrogant attitude, pointing me to useless examples or a documentation from another version of the lib, not answering any of my questions. I mean what is this? Is he annoyed by people not understanding this shitty undocumented code?

**Comment by overflowz** [comment] 2021-04-26 22:11
Listen here buddy, it's not about fame. I also needed types for v5 so instead of keeping them for myself only, I opened a PR here for everyone to be able to use it. If you really read that ticket/PR, you'd see that it got rejected, because it was lacking documentation. All I did was that I updated v4 types to v5 (with its documentation).

Do keep in mind that we also have our lives too. If you don't like it, just don't use it. If you like it, but something is blocking you from using it, feel free to contribute. Otherwise, enjoy whatever you have for free.

**Comment by overflowz** [comment] 2021-04-26 22:13
Dude, if you can't find the documentation, go check the source code. There's also a function called 'bindSync' in v5, use that if you really want it (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52566#diff-c42415d6490dc2f90be2f7990b66bed0eded33f89cbd87fa6b1b5b4acc3871afR164)

**Comment by aminya** [comment] 2021-04-26 22:19
The discussion here has served its purpose, and the issue is solved. Any contribution that solves the issues is appreciated. 

I am closing this issue because it violates the code of conduct.
https://zeromq.org/community/code-of-conduct/

**Closed by aminya** 2021-04-26 22:19 UTC
Labels: bug, question
