### ISSUE TITLE
How to use curveKeyPair?

### ISSUE THREAD

**Issue by gameprem** [zeromq/zeromq.js#657] opened 2024-09-29 17:49 UTC
Version: 6.0.4

1. Question: How can I use the curveKeyPair function? 
Result: Error: Operation not supported

2. Question: Based on the following code, how can I assign values to curveServerKey, curvePublicKey, and curveSecretKey?
const _ZMQ = require("zeromq");

const subKeyPair = _ZMQ.curveKeyPair();

const sock = new _ZMQ.Subscriber({
    curveServerKey: 'xxx',
    curvePublicKey: subKeyPair.publicKey,
    curveSecretKey: subKeyPair.secretKey,
});
Result: super(2 /* SocketType.Subscriber */, options);
TypeError: Cannot add property curveServerKey, object is not extensible

**Comment by aminya** [comment] 2024-10-02 20:40
Duplicate of #654 

You can expedite the process by sponsoring the project
https://github.com/sponsors/aminya
https://polar.sh/aminya/
https://www.patreon.com/aminya

**Closed by aminya** 2024-10-02 20:40 UTC
Labels: enhancement
