### ISSUE TITLE
Just release v6.18.0 already

### ISSUE THREAD

**Issue by coolaj86** [zeromq/zeromq.js#575] opened 2023-06-25 03:43 UTC
v6 has been in beta since `Nov 4, 2019` (nearly 4 years) and it appears that v5 is not being maintained for current versions of node (fails on v20 requiring C tools and such to build from source).

Also, v6 is the default install when running `npm install --save zeromq`

If production deploys are supposed to be using v6, that's _not_ beta.

Since v6 is being actively maintained for current node releases and v5 is not, why not drop the scary banner, go full-on v6.18.0.

... unless v6 is still subject to breaking changes.

If v6 is still subject to breaking changes, it shouldn't be the default install.

If it isn't, just bump it and go! 🚀

Re: #529

**Comment by aminya** [comment] 2023-06-25 04:06
Duplicate of #529

**Closed by aminya** 2023-06-25 04:06 UTC
