### ISSUE TITLE
It is useless in many cases without Curve

### ISSUE THREAD

**Issue by r-ss** [zeromq/zeromq.js#659] opened 2024-10-02 12:24 UTC
It's hard for me to imagine how many hours developers kill trying to get Curve to work before they find out that Curve is not in the binary. This should be written in big letters at the top of the Readme.

**Comment by aminya** [comment] 2024-10-02 20:40
Duplicate of #654 

You can expedite the process by sponsoring the project
https://github.com/sponsors/aminya
https://polar.sh/aminya/
https://www.patreon.com/aminya

**Closed by aminya** 2024-10-02 20:40 UTC
Labels: enhancement
